version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: diego
    volumes:
      - ./src/main/resources/postgres/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./src/main/resources/postgres/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql